#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

lxterminal &

chromium-browser --disable-smooth-scrolling --no-default-browser-check --no-first-run &

/usr/bin/startfluxbox
