#!/usr/bin/env bash

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $BASH_SOURCE)" && pwd -P)

source "${CURRDIR}/utils.sh"

sudo apt-get update -q

sudo apt-get install -y \
  bash-completion \
  build-essential \
  coreutils \
  curl \
  exuberant-ctags \
  jq \
  less \
  lsof \
  nmap \
  make \
  ruby \
  silversearcher-ag \
  tmux \
  unzip \
  vim-nox \
  wget \
