#!/usr/bin/env bash

set -e

if [[ ! "$(uname -s)" =~ Darwin ]]; then
  echo "Only needed on macOS, all done"
  exit 0
fi

if [[ -z $(command -v brew) ]]; then
  echo "Please install Homebrew first"
  exit 1
fi

CURRDIR=$(cd "$(dirname $BASH_SOURCE)" && pwd -P)
source "${CURRDIR}/utils.sh"

# ---------------- #
# --- Formulae --- #
# ---------------- #

# NOTE: docker is installed as cask (desktop app), because even if a docker
# formulae exists, that requires VirtualBox.

brew install \
  bash \
  bat \
  bmon \
  cmark \
  coreutils \
  diffutils \
  fd \
  ffmpeg \
  findutils \
  fzf \
  gawk \
  git \
  gnu-getopt \
  gnu-indent \
  gnu-sed \
  gnu-tar \
  gnu-time \
  gnu-which \
  gnupg \
  go \
  golangci/tap/golangci-lint \
  gpatch \
  graphviz \
  grep \
  gzip \
  htop \
  imagemagick \
  inetutils \
  jq \
  kubectx \
  less \
  lf \
  libpq \
  libxml2 \
  lsof \
  make \
  mosh \
  mtr \
  nano \
  nethogs \
  nload \
  nmap \
  openssh \
  perl \
  pre-commit \
  python \
  ranger \
  rbenv \
  ripgrep \
  rsync \
  ruby-install \
  slurm \
  sqlite \
  the_silver_searcher \
  tmux \
  trash \
  tree \
  vim \
  watch \
  wdiff \
  wget \
  zsh

# universal-ctags is a head-only formula until considered stable
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

# --------------------------------- #
# --- Post install for formulae --- #
# --------------------------------- #

printf "\n===> Configuring fzf\n"
set -x
/usr/local/opt/fzf/install --key-bindings --completion --no-update-rc
set +x

printf "\n===> Enabling brew-installed shells\n\n"
append_if_missing /etc/shells "/usr/local/bin/bash"
append_if_missing /etc/shells "/usr/local/bin/zsh"

# ------------- #
# --- Casks --- #
# ------------- #

brew cask install \
  docker \
  firefox \
  font-inconsolata \
  iterm2 \
  rectangle \
  visual-studio-code

# ------------------------------ #
# --- Post install for casks --- #
# ------------------------------ #

# --- autocompletions

ZSH_SITE_FUNCTIONS=/usr/local/share/zsh/site-functions

if [[ -d "${ZSH_SITE_FUNCTIONS}" ]]; then
  pushd "${ZSH_SITE_FUNCTIONS}"
  ln -sfv /Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion _docker
  ln -sfv /Applications/Docker.app/Contents/Resources/etc/docker-compose.zsh-completion _docker-compose
  kubectl completion zsh > _kubectl
  popd
fi

# ------------------ #
# --- Next steps --- #
# ------------------ #

echo "

NOTES

* Many packages installed depend on the shell configuration provided.
  Run './scripts/dotfiles' to install it.

* Other packages that are commonly useful:

  - binutils
  - ed
  - emacs
  - gdb
  - gnu-units
  - screen
  - unrar
  - unzip

* Other casks that could be useful:

  - google-drive-file-stream (for G Suite accounts, supports Shared Drives)
  - google-backup-and-sync (for personal accounts, works with G Suite, but does not support Shared Drives)
  - virtualbox
  - virtualbox-extension-pack
  - vagrant
  - copyq (clipboard manager that supports images)
  - vlc
"
