#!/usr/bin/env zsh

CURRENT_DC=
if [[ -z "$(command -v docker-compose)" ]]; then
  echo "docker-compose not currently installed"
  CURRENT_DC=0
else
  CURRENT_DC=$(docker-compose version --short)
fi

LATEST_DC="$(
	basename "$(
    curl -ILs -o /dev/null -w '%{url_effective}' \
      https://github.com/docker/compose/releases/latest
	)"
)"

# If the current version is greater or equal to the latest...
if [[ "${CURRENT_DC}" == $(echo -e "${CURRENT_DC}\n${LATEST_DC}" | sort -rV | head -n1) ]]; then
  echo "Current docker-compose ${CURRENT_DC} is already the latest"
else
  echo "Updating from ${CURRENT_DC} to ${LATEST_DC}"

  sudo rm -f /usr/local/bin/docker-compose

  echo "Installing '/usr/local/bin/docker-compose'"
  sudo bash -c "
  curl -L 'https://github.com/docker/compose/releases/download/${LATEST_DC}/docker-compose-$(uname -s)-$(uname -m)' \
    > '/usr/local/bin/docker-compose'
  "

  sudo chmod +x "/usr/local/bin/docker-compose"

  if [[ -d /etc/bash_completion.d ]]; then
    echo "Installing /etc/bash_completion.d/docker-compose"
    sudo bash -c "
      curl -L 'https://raw.githubusercontent.com/docker/compose/$(/usr/local/bin/docker-compose version --short)/contrib/completion/bash/docker-compose' \
        > /etc/bash_completion.d/docker-compose
    "
  fi

  echo "Installed docker-compose: "
  /usr/local/bin/docker-compose version
fi
