#!/usr/bin/env bash

set -e

sudo dnf remove -y \
  docker\
  docker-client\
  docker-client-latest\
  docker-common\
  docker-latest\
  docker-latest-logrotate\
  docker-logrotate\
  docker-selinux\
  docker-engine-selinux\
  docker-engine

sudo dnf -y install dnf-plugins-core

sudo dnf config-manager --add-repo -y https://download.docker.com/linux/fedora/docker-ce.repo

sudo dnf install -y docker-ce docker-ce-cli containerd.io

sudo usermod -aG docker $USER

sudo systemctl start docker

newgrp docker

docker run hello-world
