#!/usr/bin/env bash

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $BASH_SOURCE)" && pwd -P)

source "${CURRDIR}/utils.sh"

backup_and_symlink $ROOTDIR/gitconfig_addons $HOME/.gitconfig_addons
backup_and_symlink $ROOTDIR/bash_aliases_addons $HOME/.bash_aliases_addons
backup_and_symlink $ROOTDIR/bashrc_addons $HOME/.bashrc_addons
backup_and_symlink $ROOTDIR/tmux.conf $HOME/.tmux.conf

append_if_missing "$HOME/.bashrc" '[[ -e "${HOME}/.bashrc_addons" ]] && source ~/.bashrc_addons'
append_if_missing "$HOME/.bashrc" '[[ -e "${HOME}/.bash_aliases_addons" ]] && source ~/.bash_aliases_addons'

git config --global include.path .gitconfig_addons
