#!/usr/bin/env bash

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(git rev-parse --show-toplevel)
DOTFILES_DIR="${ROOTDIR}/dotfiles"
SCRIPTS_DIR="${ROOTDIR}/scripts"

source "${CURRDIR}/utils.sh"

HOMEBREW_PREFIX=$(usr_local)

export PATH="$HOMEBREW_PREFIX/bin:$PATH"

LOCAL_BIN="$HOME/.local/bin"

mkdir -p $LOCAL_BIN
mkdir -p "$HOME/.config"

# ----------- #
# --- git --- #
# ----------- #

backup_and_symlink "${DOTFILES_DIR}/gitconfig_addons" "${HOME}/.gitconfig_addons"
backup_and_symlink "${DOTFILES_DIR}/gitignore_global" "${HOME}/.gitignore_global"

# Some settings require the full path of the referenced file, so we need to set
# them globally (in '~/.gitconfig')
git config --global include.path ~/.gitconfig_addons
git config --global core.excludesfile ~/.gitignore_global

# ------------ #
# --- tmux --- #
# ------------ #

backup_and_symlink "${DOTFILES_DIR}/tmux.conf" "${HOME}/.tmux.conf"

# Compile tmux specific terminfo profiles with "tic" to support italics inside
# tmux.
#
# Some system might already have them, but in April 2021 most still don't
# provide them.
#
# The profiles will be compiled to ~/.terminfo.
#
tic "${ROOTDIR}/dotfiles/tmux.terminfo"
tic "${ROOTDIR}/dotfiles/tmux-256color.terminfo"

# ------------------- #
# --- miscellanea --- #
# ------------------- #

"${CURRDIR}/nnn-plugins"

LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"

backup_and_symlink "$DOTFILES_DIR/ignore" "$LOCAL_CONFIG/fd/ignore"
backup_and_symlink "$DOTFILES_DIR/ripgreprc" "$HOME/.ripgreprc"
backup_and_symlink "$DOTFILES_DIR/ignore" "$HOME/.rgignore"
backup_and_symlink "$DOTFILES_DIR/htoprc" "$LOCAL_CONFIG/htop/htoprc"
backup_and_symlink "$DOTFILES_DIR/sqliterc" "$HOME/.sqliterc"
backup_and_symlink "$DOTFILES_DIR/lfrc" "$LOCAL_CONFIG/lf/lfrc"
backup_and_symlink "$DOTFILES_DIR/tigrc" "$HOME/.tigrc"
backup_and_symlink "$DOTFILES_DIR/bat_config" "$LOCAL_CONFIG/bat/config"
backup_and_symlink "$DOTFILES_DIR/direnvrc" "$HOME/.direnvrc"
backup_and_symlink "$DOTFILES_DIR/curlrc" "$HOME/.curlrc"

# ----------------------- #
# --- custom commands --- #
# ----------------------- #

backup_and_symlink "$SCRIPTS_DIR/brut" "$LOCAL_BIN/brut"
backup_and_symlink "$SCRIPTS_DIR/epochms" "$LOCAL_BIN/epochms"
backup_and_symlink "$SCRIPTS_DIR/free" "$LOCAL_BIN/free"
backup_and_symlink "$SCRIPTS_DIR/gddirs" "$LOCAL_BIN/gddirs"
backup_and_symlink "$SCRIPTS_DIR/go-test" "$LOCAL_BIN/go-test"
backup_and_symlink "$SCRIPTS_DIR/macos-updates" "$LOCAL_BIN/macos-updates"
backup_and_symlink "$SCRIPTS_DIR/nauniq" "$LOCAL_BIN/nauniq"
backup_and_symlink "$SCRIPTS_DIR/utcnow" "$LOCAL_BIN/utcnow"
backup_and_symlink "$SCRIPTS_DIR/wanip" "$LOCAL_BIN/wanip"
backup_and_symlink "$SCRIPTS_DIR/anygit" "$LOCAL_BIN/anygit"

backup_and_symlink "$SCRIPTS_DIR/hgo-dep-versions" "$LOCAL_BIN/hgo-dep-versions"
backup_and_symlink "$SCRIPTS_DIR/hgo-test" "$LOCAL_BIN/hgo-test"

# -------------- #
# --- shells --- #
# -------------- #

backup_and_symlink "$DOTFILES_DIR/shell_addons" "$HOME/.shell_addons"
backup_and_symlink "$DOTFILES_DIR/bashrc" "$HOME/.bashrc"
backup_and_symlink "$DOTFILES_DIR/zshrc" "$HOME/.zshrc"
"$CURRDIR/zsh-completions"

if [[ "$(uname -s)" =~ Darwin ]]; then
  touch ~/.hushlogin # prevent the "last login" message on macOS
fi
