#!/usr/bin/env bash

set -ex

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(cd "$CURRDIR"; git rev-parse --show-toplevel)

source "${CURRDIR}/utils.sh"

sudo dnf upgrade -y

$CURRDIR/golang-packages

vim +PlugUpgrade +qall
vim +PlugUpdate +qall

if [[ -n "$(command -v pipx)" ]]; then
  pipx upgrade-all
fi
