#!/usr/bin/env bash

set -e

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(cd "$CURRDIR"; git rev-parse --show-toplevel)

sudo dnf install -y \
  bat \
  bind-utils \
  clang \
  cloc \
  cmake \
  ctags \
  direnv \
  exa \
  fd-find \
  fswatch \
  gcc \
  git \
  git-delta \
  glibc \
  groff \
  htop \
  jo \
  jq \
  lsof \
  make \
  mlocate \
  mosh \
  mtr \
  nmap \
  nnn \
  nodejs \
  ntpsec \
  openssl \
  pbzip2 \
  pigz \
  pipx \
  podman \
  python3-devel \
  python3.9 \
  ripgrep \
  rsync \
  ruby \
  sqlite \
  tar \
  tig \
  tmux \
  tree \
  unzip \
  util-linux-user \
  vim-enhanced \
  wget \
  yarnpkg \
  zip \
  zoxide \
  zsh

$ROOTDIR/scripts/dotfiles

$ROOTDIR/scripts/golang
export PATH=/usr/local/go/bin:$PATH
$ROOTDIR/scripts/golang-packages
$ROOTDIR/scripts/golang-zsh-completion

$ROOTDIR/scripts/fzf

$ROOTDIR/scripts/vim

$ROOTDIR/scripts/fedora-config

$ROOTDIR/scripts/fedora-updates

$ROOTDIR/scripts/docker-fedora
