#!/usr/bin/env bash

set -exo pipefail

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(cd "$CURRDIR"; git rev-parse --show-toplevel)

source "${ROOTDIR}/scripts/utils.sh"

# --------------------------------------- #
# --- Use existing VIM setup for root --- #
# --------------------------------------- #

sudo ln -svf -T $HOME/.vimrc             /root/.vimrc
sudo ln -svf -T $HOME/.vimrc.highlights  /root/.vimrc.highlights
sudo ln -svf -T $HOME/.vim               /root/.vim

# ------------------------------------------- #
# --- Disable SSH password authentication --- #
# ------------------------------------------- #

SSH_PASSWORD_AUTH_PATTERN='^[[:space:]]*PasswordAuthentication[[:space:]]+no'
if ! sudo grep -E $SSH_PASSWORD_AUTH_PATTERN /etc/ssh/sshd_config; then
  sudo tee -a /etc/ssh/sshd_config <<< "PasswordAuthentication no"
fi

sudo usermod -s /usr/bin/zsh $(whoami)
