#!/usr/bin/env bash

function free() {
  local total=$(sysctl -n hw.memsize)

  local memstats=$(vm_stat)

  local page_size=$(echo "${memstats}" | head -n 1 | grep -oE '[[:digit:]]+')

  local top_summary=$(top -l 1 | head -n 10)

  local active=$(echo "${memstats}" | grep -w 'active' | grep -oE '[[:digit:]]+')
  local inactive=$(echo "${memstats}" | grep -w 'inactive' | grep -oE '[[:digit:]]+')
  local speculative=$(echo "${memstats}" | grep -w 'speculative' | grep -oE '[[:digit:]]+')
  local wired=$(echo "${memstats}" | grep -w 'wired' | grep -oE '[[:digit:]]+')
  local purgeable=$(echo "${memstats}" | grep -w 'purgeable' | grep -oE '[[:digit:]]+')
  local compressed=$(echo "${memstats}" | grep -w 'occupied by compressor' | grep -oE '[[:digit:]]+')

  local inactive_bytes=$(( $inactive * $page_size ))
  local used_bytes=$(( ($active + $wired + $speculative + $purgeable + $compressed) * $page_size ))
  local available_bytes=$(( $total - $used_bytes ))

  local GB=1073741824

  awk "BEGIN {printf \"%-6s %s\n\", \"UPTIME\", \"$(uptime | sed -E 's/^.*up ([^,]+).+$/\1/')\"}"
  awk "BEGIN {printf \"%-6s %s\n\", \"LOAD\", \"$(echo "${top_summary}" | grep 'Load' | sed -E 's/^[^0-9]*([0-9]+.*$)/\1/')(1/5/15 min)\"}"
  awk "BEGIN {printf \"%-6s %.2f GB used (+%.2f inactive) of %.f GB total\n\", \"RAM\", ($used_bytes / $GB), ($inactive_bytes / $GB), ($total / $GB)}"
  awk "BEGIN {printf \"%-6s %s\n\", \"SWAP\", \"$(sysctl -n vm.swapusage | sed -E 's/^(.+)\(.*$/\1/')\"}"
  awk "BEGIN {printf \"%-6s %s\n\", \"DISKS\", \"$(echo "${top_summary}" | grep 'Disks' | sed -E 's/.+\/(.+ read),.+\/(.+ written).*$/\1, \2/')\"}"
}

free
