#!/usr/bin/env bash

set -euo pipefail

# report all the directories that have any changes against a given branch
# or in the current work in progress

OTHER_REVISION=
if [[ $# -gt 0 ]]; then
  OTHER_REVISION=$1
fi

git diff \
  --ignore-all-space \
  --ignore-blank-lines \
  --stat \
  --name-only \
  $OTHER_REVISION \
| sed -E -s 's/^(.+)\/[^\/]*$/\1/' \
| sort -u
