#!/usr/bin/env bash

set -euo pipefail

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"

# report all the directories that have any changes against a given branch
# or in the current work in progress

OTHER_REVISION=
if [[ $# -gt 0 ]]; then
  OTHER_REVISION=$1
fi

git diff \
  --ignore-all-space \
  --ignore-blank-lines \
  --name-only \
  $OTHER_REVISION \
| onlydirs
