#!/usr/bin/env zsh

set -eu
set -o pipefail

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/utils.sh"

HOMEBREW_PREFIX=$(usr_local)

ZSH_SITE_FUNCTIONS=$HOMEBREW_PREFIX/share/zsh/site-functions

echo "[setup] Golang autocompletions"
curl \
  'https://raw.githubusercontent.com/zsh-users/zsh-completions/master/src/_golang' \
  --location \
  --time-cond "${ZSH_SITE_FUNCTIONS}/_golang" \
  --output "/tmp/_golang"

if [[ -w $HOMEBREW_PREFIX ]]; then
  mv -v /tmp/_golang $ZSH_SITE_FUNCTIONS/
else
  sudo mv -v /tmp/_golang $ZSH_SITE_FUNCTIONS/
fi
