#!/usr/bin/env bash

set -eu

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(cd "$CURRDIR"; git rev-parse --show-toplevel)

cat << EOF
-------------------------------------------------------------------------------
Go version: $(go version)
GOROOT:     $(go env GOROOT)
GOPATH:     $(go env GOPATH)
-------------------------------------------------------------------------------

EOF

pushd ~

# Editor support
go install golang.org/x/tools/cmd/goimports@latest
go install github.com/kisielk/errcheck@latest
go install github.com/koron/iferr@latest
go install github.com/josharian/impl@latest
go install github.com/jstemmer/gotags@latest
go install github.com/go-delve/delve/cmd/dlv@latest
go install golang.org/x/tools/gopls@latest
go install mvdan.cc/gofumpt@latest

# Linters
go install honnef.co/go/tools/cmd/staticcheck@latest
go install github.com/mgechev/revive@latest

# Utils
go install github.com/kyoh86/richgo@latest
go install github.com/cespare/reflex@latest
go install github.com/dundee/gdu/v5/cmd/gdu@latest

# Other
# go install github.com/xxxserxxx/gotop/v4/cmd/gotop@latest # deprecation notices when building
# go install golang.org/x/tools/cmd/present@latest
# go install github.com/asciimoo/wuzz@latest
# go install golang.org/x/exp/cmd/modgraphviz@latest
# go install github.com/jfeliu007/goplantuml/cmd/goplantuml@latest
# go install github.com/KyleBanks/depth/cmd/depth@latest

popd

echo "[setup] Install local Go scripts"
pushd $ROOTDIR/go
go install -v github.com/bravoecho/dotfiles/go/cmd/onlydirs
go install -v github.com/bravoecho/dotfiles/go/cmd/gitparse
popd

# echo "[setup] Update Go binaries for Vim"
# vim +GoUpdateBinaries +qall
