#!/usr/bin/env bash

set -e

# The Golang project does not use github releases properly (2017-10-28).
# The most reliable way is currently to parse the official Golang downloads page.
GO_VERSION=$(
  curl -gsL golang.org/dl \
    | grep -m1 'linux-amd64.tar.gz' \
    | sed -E 's/.*https:\/\/.+\/go(.+)\.linux-amd64\.tar\.gz.*/\1/'
)

CURRDIR=$(cd "$(dirname $BASH_SOURCE)" && pwd -P)
GO_WORKSPACE="${HOME}/go"

DOWNLOAD_DIR="${HOME}/Downloads"
mkdir -p "${DOWNLOAD_DIR}"

FILENAME="go${GO_VERSION}.linux-amd64.tar.gz"
URL="https://storage.googleapis.com/golang/${FILENAME}"

source "${CURRDIR}/utils.sh"

echo "Ensure go projects dirs: ${GO_WORKSPACE} and ${GO_WORKSPACE}/src"
mkdir -p "${GO_WORKSPACE}/src"

echo "Remove old installation (dir /usr/local/go)"
sudo /bin/rm -rf "/usr/local/go"

echo "Downloading ${URL}"
wget -N -P "${DOWNLOAD_DIR}" "${URL}"

echo "Extract ${DOWNLOAD_DIR}/${FILENAME} -> /usr/local"
sudo tar -C /usr/local -xzf "${DOWNLOAD_DIR}/${FILENAME}"

echo "Checking installation: $(go version) installed at $(command -v go)"
