#!/usr/bin/env bash

set -eu

latest_url=$(
  curl \
    --head \
    --location \
    --silent \
    --output /dev/null \
    --write-out %{url_effective} \
    "https://github.com/golangci/golangci-lint/releases/latest"
)

latest_version="${latest_url##*/}"

# From: https://golangci-lint.run/usage/install
curl \
  -sSfL \
  https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
| sh -s -- -b $(go env GOPATH)/bin $latest_version

golangci-lint --version
