#!/usr/bin/env bash

set -e

INSTALL_PATH=$HOME/google-cloud-sdk

if [[ -e $INSTALL_PATH ]]; then
  echo "Google Cloud SDK already installed at ~/google-cloud-sdk"
fi

DOWNLOAD_DIR=$HOME/Downloads
mkdir -p $DOWNLOAD_DIR

FILENAME="google-cloud-sdk.tar.gz"
URL=https://dl.google.com/dl/cloudsdk/release/$FILENAME

DEST=$DOWNLOAD_DIR/$FILENAME

echo "Downloading ${URL}"
curl -L -o $DEST --time-cond $DEST $URL

tar -C $HOME -xzf "$DEST"

$INSTALL_PATH/install.sh \
  --usage-reporting false \
  --command-completion false \
  --path-update false
