#!/usr/bin/env zsh

set -eu
set -o pipefail

echo "[setup] Installing iTerm2 utilities"

function iterm2_util () {
  local util=$1
  local dest="${HOME}/.local/bin/${util}"
  local url="https://iterm2.com/utilities/${util}"

  # --time-cond "${dest}" \ fetching only if more recent doesn't work due to unexpected headers
  curl \
    "${url}" \
    --location \
    --create-dirs \
    --output "${dest}"

  chmod u+x "$dest"
}

iterm2_util 'imgcat'
iterm2_util 'imgls'
