#!/usr/bin/env zsh

set -ex

if [[ ! "$(uname -s)" =~ Darwin ]]; then
  echo "Only needed on macOS, all done"
  exit 0
fi

if [[ -z $(command -v brew) ]]; then
  echo "Please install Homebrew first"
  exit 1
fi

CURRDIR=$(cd "$(dirname $0)" && pwd -P)
source "${CURRDIR}/utils.sh"

ZSH_SITE_FUNCTIONS=/usr/local/share/zsh/site-functions

# ---------------- #
# --- Formulae --- #
# ---------------- #

# NOTE: docker is installed as cask (desktop app), because even if a docker
# formulae exists, that requires VirtualBox.

# GNU utilities

brew install --formulae --quiet \
  coreutils \
  diffutils \
  findutils \
  gawk \
  gnu-getopt \
  gnu-indent \
  gnu-sed \
  gnu-tar \
  gnu-time \
  gnu-which \
  gpatch \
  grep \
  gzip \
  inetutils \
  screen \

# Other common GNU utilities are

# autoconf
# binutils
# ed
# flex
# m4
# util-linux

# Updated versions of existing tools

brew install --formulae --quiet \
  bash \
  git \
  less \
  libxml2 \
  make \
  nano \
  openssh \
  perl \
  python \
  rsync \
  sqlite \
  zsh \

# Other utilities missing on macOS

brew install --formulae --quiet \
  bat \
  bmon \
  cmark \
  colordiff \
  direnv \
  fd \
  ffmpeg \
  fzf \
  gnupg \
  go \
  golangci/tap/golangci-lint \
  graphviz \
  htop \
  httpie \
  imagemagick \
  jq \
  kubectx \
  lf \
  libpq \
  lsof \
  mosh \
  mtr \
  nethogs \
  nload \
  nmap \
  pipx \
  pre-commit \
  ranger \
  rbenv \
  ripgrep \
  ruby-install \
  slurm \
  the_silver_searcher \
  tmux \
  trash \
  tree \
  vim \
  watch \
  wdiff \
  wget \
  yq \

brew install --formulae --quiet node yarn

# universal-ctags is a head-only formula until considered stable
brew install --formulae --quiet --HEAD universal-ctags/universal-ctags/universal-ctags

# until Neovim 0.5 is released, the HEAD version is required for LSP support
brew install --formulae --quiet --HEAD neovim

# --------------------------------- #
# --- Post install for formulae --- #
# --------------------------------- #

brew link --overwrite --force python@3.9

python3 -m pip install ydiff
python3 -m pip install --user --upgrade pynvim

printf "\n===> Configuring fzf\n"
/usr/local/opt/fzf/install --key-bindings --completion --no-update-rc

echo "\n===> Enabling brew-installed shells\n\n"
append_if_missing /etc/shells "/usr/local/bin/bash"
append_if_missing /etc/shells "/usr/local/bin/zsh"

# ------------- #
# --- Casks --- #
# ------------- #

brew tap homebrew/cask-fonts

brew install --casks --quiet \
  alacritty \
  docker \
  drawio \
  firefox \
  font-go \
  font-inconsolata \
  font-juliamono \
  iterm2 \
  middle \
  rectangle \
  sdformatter \
  visual-studio-code

# ------------------------------ #
# --- Post install for casks --- #
# ------------------------------ #

# --- autocompletions

if [[ -d "${ZSH_SITE_FUNCTIONS}" ]]; then
  pushd "${ZSH_SITE_FUNCTIONS}"
  docker_completions_dir=/Applications/Docker.app/Contents/Resources/etc/
  ln -sfv "$docker_completions_dir/docker.zsh-completion" _docker
  ln -sfv "$docker_completions_dir/docker-compose.zsh-completion" _docker-compose
  kubectl completion zsh > _kubectl
  popd
fi

# TODO: Link Chrome Dictionary to Dropbox
# $HOME/Library/Application\ Support/Google/Chrome/Default/Custom\ Dictionary.txt

# ------------------------------- #
# --- Other non-brew installs --- #
# ------------------------------- #

pushd ~
GO111MODULE=on go get -u mvdan.cc/gofumpt
GO111MODULE=on go get -u mvdan.cc/gofumpt/gofumports
GO111MODULE=on go get -u honnef.co/go/tools/cmd/staticcheck
popd

# ------------------ #
# --- Next steps --- #
# ------------------ #

echo "

-------------
--- NOTES ---
-------------

* Many packages installed depend on the shell configuration provided.
  Run './scripts/dotfiles' to install it.

* Other packages that are commonly useful:

  - binutils
  - ed
  - emacs
  - gdb
  - gnu-units
  - screen
  - unrar
  - unzip

* Other casks that could be useful:

  - copyq (clipboard manager that supports images)
  - discord
  - dropbox
  - google-backup-and-sync (for personal accounts, works with G Suite, but does not support Shared Drives)
  - google-chrome
  - google-drive-file-stream (for G Suite accounts, supports Shared Drives)
  - slack
  - vagrant
  - virtualbox
  - virtualbox-extension-pack
  - vlc
  - zoomus

"
