#!/usr/bin/env zsh

set -eu
set -o pipefail

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

echo "[setup] Update natively installed Golang packages"
"${CURRDIR}/golang-packages"

echo "[setup] Update zsh completion script for Golang"
"${CURRDIR}/golang-zsh-completion"

echo "[setup] Update delta themes"
"${CURRDIR}/delta-themes"

echo "[setup] Update Vim setup"
vim +PlugUpgrade +qall
vim +PlugUpdate +qall
vim +GoUpdateBinaries +qall
"${CURRDIR}/vim-markdown-tagbar"

echo "[setup] Update Rust"
"${CURRDIR}/rust"

echo "[setup] Update curl autocomplete for zsh"
# curl has a different location for each version, we need to relink for the
# updates to be effective
ZSH_SITE_FUNCTIONS=/usr/local/share/zsh/site-functions
if [[ -d "${ZSH_SITE_FUNCTIONS}" ]]; then
  pushd "${ZSH_SITE_FUNCTIONS}"
  ln -sfv "$(echo /usr/local/Cellar/curl/*/share/zsh/site-functions/_curl)" _curl
  popd
fi

echo "[setup] Upgrade pipx packages"
pipx upgrade-all
