#!/usr/bin/env zsh

set -e

TEMP=$(mktemp -d)

curl -Lo $TEMP/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x $TEMP/minikube \
  && sudo mv $TEMP/minikube /usr/local/bin/

rm -rf $TEMP
