#!/usr/bin/env zsh

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/utils.sh"

sudo apt-get update -qq

sudo apt-get install mumble-server -yq

sudo service mumble-server enable
