#!/usr/bin/env zsh

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(git rev-parse --show-toplevel)

source "${CURRDIR}/utils.sh"

sudo apt-get update -qq

sudo apt-get install mumble-server -yq

sudo service mumble-server enable
