#!/usr/bin/env bash

set -eu
set -o pipefail

if [[ -z $(command -v curl) ]]; then
  echo "Please install curl first"
  exit 1
fi

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(git rev-parse --show-toplevel)
DOTFILES_DIR="${ROOTDIR}/dotfiles"

source "${CURRDIR}/utils.sh"

backup_and_symlink "${DOTFILES_DIR}/zshrc" "${HOME}/.zshrc"

if [[ ! -d "${HOME}/.oh-my-zsh" ]]; then
  touch "${HOME}/.zshrc"
  ohmyzsh_install="/tmp/install-ohmyzsh.sh"
  curl -o "${ohmyzsh_install}" -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  sh "${ohmyzsh_install}" --unattended --keep-zshrc
fi
