#!/usr/bin/env bash

set -eu

FILELIST="$(cat)"

declare -A SEEN

function printdir() {
  local FILEPATH=$1
  local PARENTDIR="$(dirname $FILEPATH)"

  if [[ -v "SEEN[$FILEPATH]" || -v "SEEN[$PARENTDIR]" ]]; then
    return 0
  fi

  local DIR=$([ -d "${FILEPATH}" ] && echo "${FILEPATH}" || echo "${PARENTDIR}")

  SEEN[$DIR]="true"

  echo "$DIR"
}

# both the "for" and the "read" version are dreadfully slow, even though they
# are reading from a variable
IFS='
'
for ITEM in $FILELIST; do
  printdir $ITEM
done

# while IFS= read -r FILEPATH; do
#   printdir $FILELIST
# done <<< "$FILELIST"
