#!/usr/bin/env bash

set -eux
set -o pipefail

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"
ROOTDIR=$(git rev-parse --show-toplevel)
PLANTUML_DIR="${ROOTDIR}/../plantuml-server"

if [[ ! -d $PLANTUML_DIR ]]; then
  git clone https://github.com/plantuml/plantuml-server.git $PLANTUML_DIR
fi

pushd $PLANTUML_DIR

git pull

docker image build --pull -f Dockerfile.jetty -t local/plantuml-server:jetty .

popd
