#!/usr/bin/env bash

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $BASH_SOURCE)" && pwd -P)

source "${CURRDIR}/utils.sh"

if [[ -d ~/.rbenv ]]; then
  pushd ~/.rbenv
  git pull
  popd
else
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
fi

if [[ -d ~/.rbenv/plugins/ruby-build ]]; then
  pushd ~/.rbenv/plugins/ruby-build
  git pull
  popd
else
  mkdir -p ~/.rbenv/plugins
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

if [[ -n $(echo $PATH | grep "$HOME/.rbenv/bin") ]]; then
  curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-doctor | bash
else
  echo "
rbenv is now installed, but in order to enable it, you will condfigure your
shell

either run $ROOTDIR/scripts/dotfiles or add the following to your bashrc:

    export PATH="$HOME/.rbenv/bin:$PATH"
    if [[ $(command -v rbenv) ]]; then
      eval "$(rbenv init -)"
    fi
"
fi
