#!/usr/bin/env bash

# Based on https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-16-04

set -e

# Install dependencies

sudo apt-get update -q

sudo apt-get install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev

# Rbenv

git clone https://github.com/rbenv/rbenv.git ~/.rbenv
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

cat <<-EOF
Please add the following lines to the bottom your .bashrc (or which ever shell you use)

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

Then please log out & log back in to load rbenv, and test with

type rbenv

Which should output 'rbenv is a function'
EOF
