#!/usr/bin/env bash

set -e

version=$1

if [[ -n "${version}" ]]; then
  echo "specify version"
fi

mkdir -p ~/Downloads
pushd ~/Downloads

curl \
  --location \
  -o "ruby-install-${version}.tar.gz" \
  "https://github.com/postmodern/ruby-install/archive/v${version}.tar.gz"

tar -xzvf "ruby-install-${version}.tar.gz"
pushd "ruby-install-${version}"
sudo make install

popd; popd
