#!/usr/bin/env bash

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $BASH_SOURCE)" && pwd -P)

source "${CURRDIR}/utils.sh"

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

sudo apt-get update

sudo apt-get install -y \
  coreutils \
  curl \
  exuberant-ctags \
  jq \
  less \
  make \
  ruby \
  silversearcher-ag \
  tmux \
  unzip \
  vim-nox \
  wget \
	nodejs \
	build-essential \

sudo npm install eslint --global

# Dotfiles
backup_and_symlink $ROOTDIR/gitconfig_addons $HOME/.gitconfig_addons
backup_and_symlink $ROOTDIR/bash_aliases_addons $HOME/.bash_aliases_addons
backup_and_symlink $ROOTDIR/bashrc_addons $HOME/.bashrc_addons
backup_and_symlink $ROOTDIR/tmux.conf $HOME/.tmux.conf
backup_and_symlink $ROOTDIR/vimrc $HOME/.vimrc

# Bash
append_if_missing "$HOME/.bashrc" '[[ -e "${HOME}/.bashrc_addons" ]] && source ~/.bashrc_addons'
append_if_missing "$HOME/.bashrc" '[[ -e "${HOME}/.bash_aliases_addons" ]] && source ~/.bash_aliases_addons'

# Git
git config --global include.path .gitconfig_addons

# Vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
if [[ -n "$(command -v go)" ]]; then
  vim +GoInstallBinaries +qall
else
  echo "Golang is not installed, skipping vim-go binaries"
fi

echo "

Installation complete, please restart your session.

"
