#!/usr/bin/env zsh

set -e

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source $ROOTDIR/scripts/debian-packages

source $ROOTDIR/scripts/dotfiles

source $ROOTDIR/scripts/docker
source $ROOTDIR/scripts/docker-compose

source $ROOTDIR/scripts/google-cloud-sdk

source $ROOTDIR/scripts/mosh

source $ROOTDIR/scripts/rbenv

source $ROOTDIR/scripts/golang
source $ROOTDIR/scripts/nodejs
source $ROOTDIR/scripts/vim

# -----------------------
# --- Success message ---
# -----------------------
echo "
---------------------------------------------------
---------------------------------------------------

Installation complete, please restart your session.

---------------------------------------------------
---------------------------------------------------
"
