#!/usr/bin/env bash

# NOTE: run from the root of a diagram repository.

set -ex

docker run \
  --name=plantuml \
  --rm \
  -d \
  -p 56789:8080 \
  -w /usr/diagrams \
  -v "$(pwd):/usr/diagrams" \
  -e ALLOW_PLANTUML_INCLUDE=true \
  -e PLANTUML_LIMIT_SIZE=8192 \
  local/plantuml-server:jetty
