#!/usr/bin/env zsh

set -eu
set -o pipefail

if [[ -z $(command -v git) ]]; then
  echo "Please install git first"
  exit 1
fi

if [[ -z $(command -v curl) ]]; then
  echo "Please install curl first"
  exit 1
fi

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(dirname "$(readlink $0)")
DOTFILES_DIR="${ROOTDIR}/dotfiles"

source "${CURRDIR}/utils.sh"

backup_and_symlink "${DOTFILES_DIR}/vimrc" "${HOME}/.vimrc"

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +qall

if [[ -n "$(command -v go)" ]]; then
  vim +GoInstallBinaries +qall
else
  echo "Golang is not installed, skipping vim-go binaries"
fi

mkdir -pv ~/.vim/{backup,swp,undo,fzf-history}

backup_and_symlink "${HOME}/Dropbox/private/dotfiles/vim/spell/en.utf-8.add" "${HOME}/.vim/spell/en.utf-8.add"

"${CURRDIR}/vim-markdown-tagbar"
