#!/usr/bin/env zsh

set -e

if [[ -z $(command -v curl) ]]; then
  echo "Please install curl first"
  exit 1
fi

echo "[setup][vim] Add markdown support to TagBar"

mkd2ctags_path="${HOME}/.vim/tools/markdown2ctags"

curl -fLo "${mkd2ctags_path}" --create-dirs \
  https://raw.githubusercontent.com/jszakmeister/markdown2ctags/master/markdown2ctags.py

chmod -v u+x "${mkd2ctags_path}"
