#!/usr/bin/env zsh

set -e

ROOTDIR=$(git rev-parse --show-toplevel)
CURRDIR=$(cd "$(dirname $0)" && pwd -P)
DOTFILES_DIR="${ROOTDIR}/dotfiles"

source "${CURRDIR}/utils.sh"

sudo apt-get update -qq

sudo apt-get install -yq \
  tigervnc-standalone-server \
  fluxbox \
  x11-xkb-utils \
  chromium-browser \
  lxterminal \

backup_and_symlink "${DOTFILES_DIR}/xstartup" "${HOME}/.vnc/xstartup"

echo "
You can now start the VNC server with

    vncserver -geometry 1280x800

...and stop it with

    vncserver -kill

When connecting you will find Chromium and a terminal already running.

See also ~/.vnc/xstartup on how to run the browser.
"
