#!/usr/bin/env zsh

set -eux
set -o pipefail

CURRDIR="$(cd "$(dirname "$([ -L "${0}" ] && readlink "${0}" || echo "${0}")")" && pwd -P)"

source "${CURRDIR}/utils.sh"

HOMEBREW_PREFIX=$(usr_local)

echo "[setup] Update version-dependent zsh completion scripts"

mkdir -p "$HOME/.config/zsh/site-functions"

ZSH_SITE_FUNCTIONS=$HOME/.config/zsh/site-functions

if [[ -n "$(command -v kubectl)" ]]; then
  echo "[setup] Kubernetes autocompletions"
  kubectl completion zsh > "${ZSH_SITE_FUNCTIONS}/_kubectl"
fi

if [[ -d "$HOMEBREW_PREFIX/Cellar/curl" ]]; then
  echo "[setup] curl autocompletions"
  ln -sfv "$(echo $HOMEBREW_PREFIX/Cellar/curl/*/share/zsh/site-functions/_curl)" "${ZSH_SITE_FUNCTIONS}/_curl"
fi

DOCKER_COMPLETIONS_DIR="/Applications/Docker.app/Contents/Resources/etc"
if [[ -d $DOCKER_COMPLETIONS_DIR ]]; then
  echo "[setup] Docker autocompletions"
  ln -sfv "$DOCKER_COMPLETIONS_DIR/docker.zsh-completion" "${ZSH_SITE_FUNCTIONS}/_docker"
  ln -sfv "$DOCKER_COMPLETIONS_DIR/docker-compose.zsh-completion" "${ZSH_SITE_FUNCTIONS}/_docker-compose"
fi

WATSON_AUTOCOMPLETE="$HOMEBREW_PREFIX/opt/watson/share/zsh/site-functions/_watson"
if [[ -f $WATSON_AUTOCOMPLETE ]]; then
  ln -sfv $WATSON_AUTOCOMPLETE "$ZSH_SITE_FUNCTIONS/_watson"
fi

TIMETRAP_AUTOCOMPLETE=$(echo $HOMEBREW_PREFIX/lib/ruby/gems/*/gems/timetrap*/completions/zsh/_t | tr ' ' '\n' | head -n 1)
if [[ -f $TIMETRAP_AUTOCOMPLETE ]]; then
  ln -sfv $TIMETRAP_AUTOCOMPLETE "${ZSH_SITE_FUNCTIONS}/_t"
fi

if [[ -n "$(command -v yq)" ]]; then
  echo "[setup] yq autocompletions"
  yq shell-completion zsh > "${ZSH_SITE_FUNCTIONS}/_yq"
fi

"$CURRDIR/golang-zsh-completion"
